[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "folium>=0.19.5",
    "geopandas>=1.0.1",
    "streamlit-folium>=0.25.0",
    "streamlit>=1.44.1",
    "plotly>=6.0.1",
    "pyogrio>=0.10.0",
]
